PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "beastiary" ("id" TEXT, "chance" TEXT, "entity" TEXT, "entityEffect" TEXT, "difficulty" TEXT, "iconURL" TEXT);
INSERT INTO beastiary VALUES('Initiate1','0.5','The Deadline Demon','A project due date approaches too quickly!','1','NULL');
INSERT INTO beastiary VALUES('Initiate2','0.4','The Sleep-Stealing Specter','A restless mind delays sleep!','2','NULL');
INSERT INTO beastiary VALUES('Initiate3','0.5','The Wi-Fi Banshee','The internet dies before a submission!','1','NULL');
INSERT INTO beastiary VALUES('Initiate4','0.35','The Multiple-Choice Menace','Two answers seem correctthou must guess blindly!','2','NULL');
INSERT INTO beastiary VALUES('','','','','','');
INSERT INTO beastiary VALUES('Collegiate1','0.5','The Lecture Lurker','A professor cold-calls thee when unprepared!','1','NULL');
INSERT INTO beastiary VALUES('Collegiate2','0.4','The Group Project Ghoul','A teammate vanishes before the deadline!','2','NULL');
INSERT INTO beastiary VALUES('Collegiate3','0.5','The Multiple-Choice Menace','Two answers seem correctthou dost guess blindly!','1','NULL');
INSERT INTO beastiary VALUES('Collegiate4','0.35','The Wi-Fi Banshee','The internet dies moments before submission!','2','NULL');
INSERT INTO beastiary VALUES('','','','','','');
INSERT INTO beastiary VALUES('Pedagogue1','0.5','The Lesson Lurker','A pupil asks a question on a topic thou hast not planned for.','1','NULL');
INSERT INTO beastiary VALUES('Pedagogue2','0.4','The Curriculum Ghoul','The textbook thou art given is too complex or too short for thy lesson.','2','NULL');
INSERT INTO beastiary VALUES('Pedagogue3','0.5','The Apathy Menace','The pupils fall asleep while thou art teaching!','1','NULL');
INSERT INTO beastiary VALUES('Pedagogue4','0.35','The Interactive Whiteboard Banshee','Thy prepared presentation glitches moments before the lesson begins!','2','NULL');
INSERT INTO beastiary VALUES('','','','','','');
INSERT INTO beastiary VALUES('Masters1','0.5','Reviewer #2’s Wrath','Even the best research is not acceptable!','1','NULL');
INSERT INTO beastiary VALUES('Masters2','0.4','The Citation Phantom','A critical source disappears forever!','2','NULL');
INSERT INTO beastiary VALUES('Masters3','0.5','The Midnight Panic','A brilliant idea arrivesat 3 AM!','1','NULL');
INSERT INTO beastiary VALUES('Masters4','0.35','The Funding Wraith','The proposal is praised, yet denied!','2','NULL');
INSERT INTO beastiary VALUES('','','','','','');
INSERT INTO beastiary VALUES('Doctoral1','0.5','Reviewer #2’s Wrath','No matter how perfect, it is not enough!','1','NULL');
INSERT INTO beastiary VALUES('Doctoral2','0.4','The Deadline Wraith','The committee pushes back thy defense date!','2','NULL');
INSERT INTO beastiary VALUES('Doctoral3','0.5','The Imposter Syndrome Phantom','Doubt creeps in: art thou truly worthy of the Ph.D.?','1','NULL');
INSERT INTO beastiary VALUES('Doctoral4','0.35','The Eternal Wait','Thou hast submitted a grant… and now thou shalt wait.','2','NULL');
INSERT INTO beastiary VALUES('','','','','','');
INSERT INTO beastiary VALUES('Sage1','0.5','Reviewer #2’s Curse','No matter how polished thy work, it shall never be enough!','1','NULL');
INSERT INTO beastiary VALUES('Sage2','0.4','The Accreditation Hydra','Institutional reviews multiply!','2','NULL');
INSERT INTO beastiary VALUES('Sage3','0.5','The Scheduling Sphinx','All meetings conflict with thy research hours!','1','NULL');
INSERT INTO beastiary VALUES('Sage4','0.35','The Funding Wraith','Thy proposal is praised, yet denied funding!','2','NULL');
INSERT INTO beastiary VALUES('','','','','','');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Impending Deadline Fiend','Lurks ever closer, whispering doom, yet never granting thee focus.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Footnote Gremlin','Scrambles citations at random, forcing thee to spend precious time in correction.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Coffee Chimera ☕','Promises energy but delivers anxiety, jitters, and impending doom!','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Invisible Tangle Sprite 🌀','Moves objects just slightly out of reach, making cleanup thrice as long!','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Scheduling Sphinx','Ensures all meetings are scheduled at the worst possible time.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Disappearing Student','Signs up for thy class, submits no work, and ghosts entirely.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Goblin of Perpetual Fatigue 💤','Whispers sweet nothings of “Thou art too weary to engage in self-care today…”','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Sleepless Wraith','Haunts thee with restlessness, ensuring no sleep before a deadline.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Forgotten Meal Specter','Ensures thy stomach growls but thy hands remain too busy to eat.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Pigeon of Peril','Strikes unsuspecting scholars from above, bringing momentary humiliation.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Infinite Scroll Wraith 📱','Ensnares the scholar in an endless loop of doomscrolling instead of self-care!','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Horde of Emails','A single email begets twenty more, none with clear purpose.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Infinite Revisions Wraith','Ensures thy draft is never ‘ready’ for submission.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.5','The Decision Paralysis Gargoyle 🤯','Leaves thee staring at thy tea selection, unable to choose one before thy water grows cold.','1','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.3','The Lecture Lich','Drains the energy from a room, ensuring no one participates.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.3','The Treasurer’s Frown','Delays funding approvals with cryptic denials.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.3','The Midnight Muse','Blesses thee with a genius ideaat 3 AM, at the cost of rest.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.3','The Citation Phantom','Erases a critical reference from thy notes, causing a frantic search.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.3','The Vanishing Towel Phantom 🏴','The towel that was there is now no longer there.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.35','The Paperwork Mimic','Transforms completed forms into outdated versions, requiring resubmission.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.35','The Shampoo Bottle Djinn 🚿','Ensures one necessary hygiene item is missing only after thou art already wet!','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.4','The Blanket of Eternal Rest 🛌','Thou didst lie down… and now thou shalt not rise for many hours!','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.4','The Endless Thread Curse','Causes a single email to generate infinite follow-ups.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.4','The Endless Thread Curse','Ensures no email chain ever truly ends.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.4','The Jargon Djinn','Transforms thy words into an unreadable mess, requiring multiple revisions.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.4','The Sensory Overwhelm Wraith 🎭','Ensures a loud noise, bright light, or strong smell derails thee from relaxation.','2','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.2','The Unread Reviewer','Dismisses thy work outright, with feedback that proves they never read it.','3','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.2','The Unmovable Dean','Rejects all requests for change, citing ‘tradition’ as law.','3','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.25','The Grant Demon','Inserts vague and contradictory feedback, leading to confusion and despair.','3','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.25','The HR Hydra','Requires an endless stream of forms, approvals, and training modules.','3','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.25','The Plagiarism Poltergeist','Haunts thee with false accusations, demanding thou prove thy innocence!','3','NULL');
INSERT INTO beastiary VALUES('randomPeril','0.2','The Elder Examiner’s Wrath','A grand and impossible question is delivered with a solemn gaze.','3','NULL');
INSERT INTO beastiary VALUES('','','','','','');
INSERT INTO beastiary VALUES('miniquest1','0.2','The Wandering Mind Phantom','Halfway through, thou dost forget what thou read!','1','NULL');
INSERT INTO beastiary VALUES('miniquest2','0.35','Ink Goblin','Thine highlighter is missing or has dried up!','1','NULL');
INSERT INTO beastiary VALUES('miniquest3','0.3','Jargon Djinn','Thou dost struggle to phrase it simply!','1','NULL');
INSERT INTO beastiary VALUES('miniquest4','0.5','Notification Gremlin','An alert, sound, or thought derails thee!','1','NULL');
INSERT INTO beastiary VALUES('miniquest5','0.35','Perfectionistâ€™s Shadow','Thou dost hesitate, doubting the worth of the first word!','1','NULL');
INSERT INTO beastiary VALUES('miniquest6','0.4','Sentence Loop Curse','Thou dost keep rewriting the same phrase!','1','NULL');
INSERT INTO beastiary VALUES('miniquest7','0.3','Footnote Gremlin','A missing citation throws thee into chaos!','1','NULL');
INSERT INTO beastiary VALUES('miniquest8','0.4','Document Demon','A required field makes no sense!','1','NULL');
INSERT INTO beastiary VALUES('miniquest9','0.35','Scheduling Sphinx','The best time is already taken!','1','NULL');
INSERT INTO beastiary VALUES('miniquest10','0.35','Tangent Djinn','Thou dost veer wildly off-topic!','1','NULL');
INSERT INTO beastiary VALUES('miniquest11','0.3','Formatting Fiend','A slide layout refuses to align properly!','1','NULL');
INSERT INTO beastiary VALUES('miniquest12','0.25','Deafening Silence of Disinterest','No student answers immediately!','1','NULL');
INSERT INTO beastiary VALUES('miniquest13','0.35','Looping Sentence Curse','Thou dost rewrite the same idea five times!','1','NULL');
INSERT INTO beastiary VALUES('miniquest14','0.4','Footnote Gremlin','A source is missing and must be found!','1','NULL');
INSERT INTO beastiary VALUES('miniquest15','0.3','Data Goblin','Numbers seem incorrect, requiring double-checking!','1','NULL');
INSERT INTO beastiary VALUES('miniquest16','0.25','Vanishing Text Demon','A section disappears mysteriously!','1','NULL');
INSERT INTO beastiary VALUES('miniquest17','0.4','Slide of Doom','A crucial figure refuses to align correctly!','1','NULL');
INSERT INTO beastiary VALUES('miniquest18','0.35','Jargon Djinn','Thou dost struggle to phrase things simply!','1','NULL');
INSERT INTO beastiary VALUES('miniquest19','0.3','Unanswerable Question','A practice query leaves thee speechless!','1','NULL');
INSERT INTO beastiary VALUES('miniquest20','0.25','Wardrobe Malfunction Gremlin','A button or zipper fails!','1','NULL');
INSERT INTO beastiary VALUES('miniquest21','0.4','Endless Wordsmithing Curse','Thou dost change it thrice and remain unsatisfied!','1','NULL');
INSERT INTO beastiary VALUES('miniquest22','0.35','Condensation Struggle','The abstract refuses to fit the word limit!','1','NULL');
INSERT INTO beastiary VALUES('miniquest23','0.35','Reference Style Wraith','The journal requires a citation format overhaul!','1','NULL');
INSERT INTO beastiary VALUES('miniquest24','0.25','Server Error Demon','The submission system crashes just after pressing submit!','1','NULL');
INSERT INTO beastiary VALUES('miniquest25','0.4','Illegible Ink Gremlin','Thou canst not decipher the studentâ€™s handwriting!','1','NULL');
INSERT INTO beastiary VALUES('miniquest26','0.35','Over-Explanation Curse','Thy feedback grows longer than the studentâ€™s work!','1','NULL');
INSERT INTO beastiary VALUES('miniquest27','0.3','Score Sheet Specter','A grading rubric is missing or inconsistent!','1','NULL');
INSERT INTO beastiary VALUES('miniquest28','0.4','Endless Thread Curse','A single email spawns five follow-ups!','1','NULL');
INSERT INTO beastiary VALUES('miniquest29','0.35','Cryptic Inquiry Gremlin','The studentâ€™s question makes no sense!','1','NULL');
INSERT INTO beastiary VALUES('miniquest30','0.3','Student No-Show Curse','None attend thy office hours, and time is lost!','1','NULL');
INSERT INTO beastiary VALUES('miniquest31','0.4','Disappearing Student','A student on the roster has never been seen!','1','NULL');
INSERT INTO beastiary VALUES('miniquest32','0.35','Paperwork Phantom','The form format is incorrect, requiring resubmission!','1','NULL');
INSERT INTO beastiary VALUES('miniquest33','0.3','Scheduling Sphinx','The ideal time slot is already taken!','1','NULL');
COMMIT;
